scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:8080']

- job_name: 'spring-actuator'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8080']

- job_name: 'test-app-metrics'
  metrics_path: '/actuator/test-endpoint'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8080']

- job_name: 'pushgateway'
  metrics_path: '/metrics'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9091']

